pipeline:
  install_dependencies:
    name: install_dependencies
    image: node:latest
    commands:
      - npm install
      - $(npm bin)/cypress verify || $(npm bin)/cypress install

  run_dev_server:
    name: run_dev_server
    image: node:latest
    commands:
      - npm run dev
    detach: true

  run_cypress_tests:
    name: run_cypress_tests
    image: cypress/browsers:latest
    commands:
      - npm run cypress:run -- --browser chrome
      - npm run cypress:run -- --browser firefox
      - npm run cypress:run -- --browser edge
