steps:
  - name: install_dependencies
    image: node:latest
    commands:
      - npm install

  - name: run_dev_server
    image: node:latest
    commands:
      - npm run dev
    detach: true

  - name: run_cypress_tests
    image: cypress/browsers:latest
    commands:
      - npm run cypress:run -- --browser chrome
      - npm run cypress:run -- --browser firefox
      - npm run cypress:run -- --browser edge
