matrix:
  BROWSER:
    - chrome
    - firefox
    - edge

steps:
  - name: install
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npm install
      - npm run build

  - name: start_server
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npm run dev-server
    detach: true

  - name: test_${BROWSER}
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npx cypress run --browser ${BROWSER}