steps:
  - name: install
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npm install
      - npx cypress verify || npx cypress install
      - npm run build
      - npm run dev-server&
      # We don't want all tests to be executed even if one fails
      - npx cypress run --browser chrome || >&2 echo "Chrome tests failed"
      - npx cypress run --browser firefox || >&2 echo "Firefox tests failed"
      - npx cypress run --browser edge || >&2 echo "Edge tests failed"