steps:
  - name: install
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npm install
      - npx cypress verify || npx cypress install

  - name: build
    commands:
      - npm run build

  - name: start_server
    commands:
      - npm run dev-server
    detach: true

  - name: test_chrome
    commands:
      - npx cypress run --browser chrome

  - name: test_firefox
    commands:
      - npx cypress run --browser firefox

  - name: test_edge
    commands:
      - npx cypress run --browser edge