steps:
  - name: install
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npm install
      - npx cypress verify || npx cypress install
    volumes:
      - /pf-iframe/root/.cache/Cypress:/root/.cache/Cypress

  - name: build
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npm run build
    volumes:
      - /pf-iframe/root/.cache/Cypress:/root/.cache/Cypress

  - name: start_server
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npm run dev-server
    volumes:
      - /pf-iframe/root/.cache/Cypress:/root/.cache/Cypress
    detach: true

  - name: test_chrome
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npx cypress run --browser chrome
    volumes:
      - /pf-iframe/root/.cache/Cypress:/root/.cache/Cypress

  - name: test_firefox
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npx cypress run --browser firefox
    volumes:
      - /pf-iframe/root/.cache/Cypress:/root/.cache/Cypress

  - name: test_edge
    image: cypress/browsers:node16.16.0-chrome107-ff107-edge
    commands:
      - npx cypress run --browser edge
    volumes:
      - /pf-iframe/root/.cache/Cypress:/root/.cache/Cypress