steps:
  - name: install_and_test
    image: cypress/browsers:latest
    commands:
      - npm install
      - npm run dev & # Start the server in the background
      - npx cypress run --browser chrome
      - npx cypress run --browser firefox
      - npx cypress run --browser edge
    detach: false
