when:
  event: tag

steps:
  - name: zipping
    image: node:20.11.1-slim
    commands:
      - mkdir -p dist/archives
      - find dist/prod -type f -printf "%P\n" | tar -czf "dist/archives/pf-iframe-${CI_COMMIT_TAG##v}-prod.tar.gz" -C dist/prod -T -
      - find dist/lib -type f -printf "%P\n" | tar -czf "dist/archives/pf-iframe-${CI_COMMIT_TAG##v}-lib.tar.gz" -C dist/prod -T -
      - find dist/prod -type f -exec sh -c "zip dist/archives/pf-iframe-${CI_COMMIT_TAG##v}-prod.zip -j {}" \;
      - find dist/lib -type f -exec sh -c "zip dist/archives/pf-iframe-${CI_COMMIT_TAG##v}-lib.zip -j {}" \;
  - name: release
    image: woodpeckerci/plugin-github-release
    settings:
      files:
        - dist/archives/*.tar.gz
        - dist/archives/*.zip
      title: ${CI_COMMIT_TAG##v}
      api-key:
        from_secret: FOSSalyze_RELEASE_GITHUB_TOKEN

depends_on:
  - build
  - e2e-tests